#define IDENTIFIER 1
#define CONSTANT 2
#define READ 3
#define WRITE 4
#define IF 5
#define ELSE 6
#define WHILE 7
#define FOR 8
#define IN 9
#define RANGE 10
#define INTEGER 11
#define STRING 12
#define CHAR 13
#define MAIN 14
